### List
GET http://127.0.0.1:8000/api/classes
Accept: application/json

### Store
POST http://127.0.0.1:8000/api/classes
Accept: application/json
Content-Type: application/json

{
  "name": "one"
}

### Show
GET http://127.0.0.1:8000/api/classes/2
Accept: application/json

### Update
PUT http://127.0.0.1:8000/api/classes/2
Accept: application/json
Content-Type: application/json

{
  "name": "Eight"
}

### Delete
DELETE  http://127.0.0.1:8000/api/classes/3
Accept: application/json