### List
GET http://127.0.0.1:8000/api/subjects
Accept: application/json

### Store
POST http://127.0.0.1:8000/api/subjects
Accept: application/json
Content-Type: application/json

{
  "name": "Bangla"
}

### Show
GET http://127.0.0.1:8000/api/subjects/1
Accept: application/json

### Update
PUT http://127.0.0.1:8000/api/subjects/2
Accept: application/json
Content-Type: application/json

{
  "name": "English"
}

### Delete
DELETE  http://127.0.0.1:8000/api/subjects/3
Accept: application/json